name: Auto-deploy-on-push
on: [push]
jobs: 
    cdk-deploy:
      if: github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
      - name: Check out our code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1
        
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend/
      - name: build-synth-and-deploy
        run: npm ci && npm run deploy
        working-directory: infra
  
          
env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
