name: GitHub Actions Demo
on: [push]
jobs: 
    cdk-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Check out our code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install depedencies
        run: npm ci
      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v2.1.1
        with:
          cdk_subcommand: 'synth'
          cdk_version: '2.20.0'
          
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
